"""Read and write Palace memory blocks in CLAUDE.md files."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import Project, PALACE_START, PALACE_END, PALACE_DIR

MEMORY_TEMPLATE = """\
# Palace Memory: {name}

> Auto-generated by Claude Code 记忆宫殿. Edit freely — this is Claude's context, not yours.

## 项目状态
_（首次使用，尚无记录。开始对话后此处会自动更新。）_

## 关键路径
- 项目目录: `{path}`

## 待办 / 进行中
_（无）_

## 最近决策
_（无）_
"""


def load_memory(project: Project) -> str:
    """Return the memory content for a project, creating template if absent."""
    project.memory_path.parent.mkdir(parents=True, exist_ok=True)
    if not project.memory_path.exists():
        content = MEMORY_TEMPLATE.format(name=project.name, path=project.path)
        project.memory_path.write_text(content, encoding="utf-8")
    return project.memory_path.read_text(encoding="utf-8")


def save_memory(project: Project, content: str) -> None:
    """Persist updated memory content."""
    project.memory_path.parent.mkdir(parents=True, exist_ok=True)
    project.memory_path.write_text(content, encoding="utf-8")


def inject_into_claude_md(project: Project) -> None:
    """Inject palace memory block into the project's CLAUDE.md."""
    memory = load_memory(project)
    palace_block = f"{PALACE_START}\n{memory}\n{PALACE_END}"

    if project.claude_md_path.exists():
        original = project.claude_md_path.read_text(encoding="utf-8")
        # Replace existing palace block or append
        if PALACE_START in original:
            import re
            pattern = re.compile(
                re.escape(PALACE_START) + r".*?" + re.escape(PALACE_END),
                re.DOTALL,
            )
            updated = pattern.sub(palace_block, original)
        else:
            updated = original.rstrip() + "\n\n" + palace_block + "\n"
    else:
        updated = palace_block + "\n"

    project.claude_md_path.write_text(updated, encoding="utf-8")


def remove_from_claude_md(project: Project) -> None:
    """Remove palace block from CLAUDE.md (clean up after session)."""
    if not project.claude_md_path.exists():
        return
    import re
    original = project.claude_md_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"\n?" + re.escape(PALACE_START) + r".*?" + re.escape(PALACE_END) + r"\n?",
        re.DOTALL,
    )
    cleaned = pattern.sub("", original).strip() + "\n"
    project.claude_md_path.write_text(cleaned, encoding="utf-8")


def list_all_projects_with_memory() -> list[tuple[str, Path]]:
    """Return (name, memory_path) for all projects that have memories."""
    result = []
    if not PALACE_DIR.exists():
        return result
    for mem in sorted(PALACE_DIR.glob("*/memory.md")):
        result.append((mem.parent.name, mem))
    return result
