"""Read and write Palace memory blocks in CLAUDE.md files."""
from __future__ import annotations

import re
from pathlib import Path

from .models import Project, PALACE_START, PALACE_END, PALACE_DIR

MEMORY_TEMPLATE = """\
# Palace Memory: {name}

> Auto-generated by Claude Code 记忆宫殿.

## Project Fields
{fields_section}

## 项目状态
_（首次使用，尚无记录。）_

## 待办
_（无）_

## 最近决策
_（无）_
"""


def _fields_md(project: Project) -> str:
    if not project.fields:
        return "_（无字段，请在 Palace 界面添加）_"
    lines = []
    for k, v in project.fields.items():
        lines.append(f"- **{k}**: `{v}`")
    return "\n".join(lines)


def load_memory(project: Project) -> str:
    project.memory_path.parent.mkdir(parents=True, exist_ok=True)
    if not project.memory_path.exists():
        content = MEMORY_TEMPLATE.format(
            name=project.name,
            fields_section=_fields_md(project),
        )
        project.memory_path.write_text(content, encoding="utf-8")
    return project.memory_path.read_text(encoding="utf-8")


def save_memory(project: Project, content: str) -> None:
    project.memory_path.parent.mkdir(parents=True, exist_ok=True)
    project.memory_path.write_text(content, encoding="utf-8")


def inject_into_claude_md(project: Project) -> None:
    """Build palace block (fields + memory) and inject into CLAUDE.md."""
    memory = load_memory(project)

    # Always regenerate fields section
    fields_block = ""
    if project.fields:
        lines = ["## Project Fields (from Palace)\n"]
        for k, v in project.fields.items():
            lines.append(f"- **{k}**: `{v}`")
        fields_block = "\n".join(lines) + "\n\n"

    palace_block = f"{PALACE_START}\n{fields_block}{memory}\n{PALACE_END}"

    if project.claude_md_path.exists():
        original = project.claude_md_path.read_text(encoding="utf-8")
        if PALACE_START in original:
            pattern = re.compile(
                re.escape(PALACE_START) + r".*?" + re.escape(PALACE_END),
                re.DOTALL,
            )
            updated = pattern.sub(palace_block, original)
        else:
            updated = original.rstrip() + "\n\n" + palace_block + "\n"
    else:
        updated = palace_block + "\n"

    project.claude_md_path.write_text(updated, encoding="utf-8")


def remove_from_claude_md(project: Project) -> None:
    if not project.claude_md_path.exists():
        return
    original = project.claude_md_path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"\n?" + re.escape(PALACE_START) + r".*?" + re.escape(PALACE_END) + r"\n?",
        re.DOTALL,
    )
    cleaned = pattern.sub("", original).strip()
    if cleaned:
        project.claude_md_path.write_text(cleaned + "\n", encoding="utf-8")
    else:
        project.claude_md_path.unlink(missing_ok=True)
